sudo: required
language: go
go:
  - master
env:
    - GIMME_OS=linux GIMME_ARCH=amd64
services:
  - docker
script:
    - go build -v ./...
    - docker build --no-cache -t niilo/clamav-rest .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push niilo/clamav-rest;
    fi