name: "Build and push docker image"

on:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/dfe-digital/clamav-rest:latest

